### ISSUE TITLE
How do i publish this to netlify?

### ISSUE THREAD

**Issue by talmax1124** [paolodelia99/Simple-node-chat-app#4]

**Comment by paolodelia99** [comment]
I don't think you can deploy this app on netlify. For the deployment I've used heroku.

**Comment by talmax1124** [comment]
ok, how do i do that

**Comment by paolodelia99** [comment]
So make an Heroku account, create a new app, and the simple way to deploy it is to connect your heroku app to to github repo.
For more details you can check out this video:
https://www.youtube.com/watch?v=MxfxiR8TVNU

**Comment by talmax1124** [comment]
is there a command for it to run? like a npm command?

**Comment by paolodelia99** [comment]
If you're connecting heroku to your github repo no command is required. You can also use npm here's the docs: https://devcenter.heroku.com/articles/deploying-nodejs
